# Generated by Django 4.1.2 on 2022-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tasks",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tags", to="todo.task"
            ),
        ),
    ]
