# Generated by Django 4.1.2 on 2022-10-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_tag_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateField(),
        ),
    ]
